language: node_js
node_js:
  - 11

services:
  - docker

install:
  - echo "No installations necessasry"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t simplicitydevs/reverse-proxy .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "simplicitydevs" --password-stdin
  - docker push simplicitydevs/reverse-proxy

